name: VabHub Deploy CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate Docker Compose files
      run: |
        docker-compose -f docker-compose.yml config
        docker-compose -f docker-compose.multi-repo.yml config
    
    - name: Validate deployment scripts
      run: |
        if [ -d "scripts/" ] && [ "$(ls -A scripts/)" ]; then
          find scripts/ -name "*.sh" -exec bash -n {} \;
          find scripts/ -name "*.py" -exec python -m py_compile {} \;
        else
          echo "No scripts found, skipping validation"
        fi

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check for secrets in scripts
      uses: gitleaks/gitleaks-action@v2
      with:
        config-path: .gitleaks.toml
      continue-on-error: true
    
    - name: Scan Docker images for vulnerabilities
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy:latest image vabhub/vabhub-core:latest

  build:
    runs-on: ubuntu-latest
    needs: [validate, security]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker images
      run: |
        docker build -t vabhub/deploy-scripts:latest .
    
    - name: Upload deployment artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vabhub-deploy-artifacts
        path: |
          scripts/
          docker/
          docker-compose*.yml